name: Update badges

on:
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:

jobs:
  update-readme:
    name: Update Readme with Credly badges

    runs-on: ubuntu-latest

    steps:
      - name: Badges - Readme
        uses: jd-35656/readme-credly-badges@refactor/v1
        with:
          COMMIT_MESSAGE: "chore: Update README with new badges."
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

